### ISSUE TITLE
Dependencies missing

### ISSUE THREAD

**Issue by MeroFuruya** [SilentJungle399/discord_buttons_plugin#1]
Dependencies such as `requests` or `discord.py` are not mentioned and missing when installing _with pypi_

**Comment by SilentJungle399** [comment]
Hello! Very sorry for the late reply. This library no longer serves any purpose since discord.py v2 already has implemented buttons.

Here is [a tutorial](https://www.youtube.com/watch?v=MAHJJaMulvo) to get started with buttons on discord.py v2.
