### ISSUE TITLE
How do I disable button after the button is clicked??

### ISSUE THREAD

**Issue by BlueDuck-jpg** [SilentJungle399/discord_buttons_plugin#11]
I wanted to make a button, and when it's clicked i want it to be disabled and also is there any way to make only the ctx.author can click the button?

**Comment by SilentJungle399** [comment]
Hello! Very sorry for the late reply. This library no longer serves any purpose since discord.py v2 already has implemented buttons.

Here is [a tutorial](https://www.youtube.com/watch?v=MAHJJaMulvo) to get started with buttons on discord.py v2.
