### ISSUE TITLE
Required attributes are optional 

### ISSUE THREAD

**Issue by MeroFuruya** [SilentJungle399/discord_buttons_plugin#2]
The attributes `label` and `custom_id` in the function `discord_buttons_plugin.models.Button.__init__()` are optional altough they are required

**Comment by SilentJungle399** [comment]
Hello! Very sorry for the late reply. This library no longer serves any purpose since discord.py v2 already has implemented buttons.

Here is [a tutorial](https://www.youtube.com/watch?v=MAHJJaMulvo) to get started with buttons on discord.py v2.
