### ISSUE TITLE
variable instead string?

### ISSUE THREAD

**Issue by MeroFuruya** [SilentJungle399/discord_buttons_plugin#3]
i'm not sure but shouldn't it say `if event not in self._listeners:` instead of `if "id" not in self._listeners:` in line `32` in `discord_buttons_plugin.__main__.ButtonsClient.add_listener()`

**Comment by SilentJungle399** [comment]
Hello! Very sorry for the late reply. This library no longer serves any purpose since discord.py v2 already has implemented buttons.

Here is [a tutorial](https://www.youtube.com/watch?v=MAHJJaMulvo) to get started with buttons on discord.py v2.
