### ISSUE TITLE
cogs

### ISSUE THREAD

**Issue by robalyy** [SilentJungle399/discord_buttons_plugin#4]

**Comment by elias-utf8** [comment]
hello when I try to integrate a button a cog I have an error message saying that 'self' is not defined
Error:
`discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ExtensionFailed: Extension 'Base' raised an error: NameError: name 'self' is not defined`
Code:
```py
def setup(bot):
	bot.add_cog(CogABase(bot))


class CogABase(commands.Cog):
	def __init__(self, bot):
		self.bot = bot		
	buttons = ButtonsClient(self.bot)

        @commands.command()
        async def button(self, ctx):
             embed = . . .
             await buttons.send(
		      content = embed, 
		      channel = ctx.channel.id,
		      components = [ActionRow([Button(label="all commands", style= ButtonType().Primary, custom_id = "button_command")])])
```

**Comment by SilentJungle399** [comment]
Hello! Very sorry for the late reply. This library no longer serves any purpose since discord.py v2 already has implemented buttons.

Here is [a tutorial](https://www.youtube.com/watch?v=MAHJJaMulvo) to get started with buttons on discord.py v2.
