### ISSUE TITLE
Some error showing up in discord

### ISSUE THREAD

**Issue by SoulFire2879** [SilentJungle399/discord_buttons_plugin#5]
![Opera Snapshot_2021-07-02_101007_discord com](https://user-images.githubusercontent.com/77575770/124221667-d7716700-db1d-11eb-84dc-7219ebc15ea7.png)

This is showing up when i click on the button, the button does work but this shows up

**Comment by bastiH96** [comment]
Yeah I have the same issue, everything works fine but I always receive this error message.

**Comment by SoulFire2879** [comment]
> Yeah I have the same issue, everything works fine but I always receive this error message.

me too , hope the developer would fix this

**Comment by MeroFuruya** [comment]
i also got this error until i added an reply at the end of the button listener function:

```py
@buttons.click
async def button_one(ctx):
    # do your stuff
    await ctx.reply("Hello!")  # thats the important thing
```
i guess if you don't do that reply thing the discord API thinks that button click action didnt work.

if you dont want to have a message, readable by everyone, sended everytime a button is klicked you can instaed write:
`await ctx.reply("Hello!", flags=64)`
that `flags=64` makes the bot return with a [**ephemeral** message](https://support.discord.com/hc/article_attachments/1500000616802/mceclip0.png) (this message is only visible to the user who invoked the Interaction and will be dismissed after some time) [source](https://discord.com/developers/docs/resources/channel#message-object-message-flags)

**Comment by ghost** [comment]
> i also got this error until i added an reply at the end of the button listener function:
> 
> ```python
> @buttons.click
> async def button_one(ctx):
>     # do your stuff
>     await ctx.reply("Hello!")  # thats the important thing
> ```
> 
> i guess if you don't do that reply thing the discord API thinks that button click action didnt work.
> 
> if you dont want to have a message, readable by everyone, sended everytime a button is klicked you can instaed write:
> `await ctx.reply("Hello!", flags=64)`
> that `flags=64` makes the bot return with a [**ephemeral** message](https://support.discord.com/hc/article_attachments/1500000616802/mceclip0.png) (this message is only visible to the user who invoked the Interaction and will be dismissed after some time) [source](https://discord.com/developers/docs/resources/channel#message-object-message-flags)

That works as well, but i just put the line `await ctx.reply()` in the listener function and it works fine, no message sended on the channel(not even in EPHEMERAL mode) and no "This interaction failed" message as well!!

**Comment by SilentJungle399** [comment]
Hello! Very sorry for the late reply. This library no longer serves any purpose since discord.py v2 already has implemented buttons.

Here is [a tutorial](https://www.youtube.com/watch?v=MAHJJaMulvo) to get started with buttons on discord.py v2.
