### ISSUE TITLE
emoji button

### ISSUE THREAD

**Issue by SoulFire2879** [SilentJungle399/discord_buttons_plugin#6]
what shud i provide in the id field of emoji button. Also when i use normal button u can use the custom id of the button in the @buttons.click to check if it was clicked, but how do i do it for the emoji coz emoji button doesnt have custom id . do i use the id field?

**Comment by SilentJungle399** [comment]
Hello! Very sorry for the late reply. This library no longer serves any purpose since discord.py v2 already has implemented buttons.

Here is [a tutorial](https://www.youtube.com/watch?v=MAHJJaMulvo) to get started with buttons on discord.py v2.
