### ISSUE TITLE
disocord Embed´s

### ISSUE THREAD

**Issue by Geruchslost** [SilentJungle399/discord_buttons_plugin#9]
can´t send embeds no matter what I try, pls fix

**Comment by ICUBICI** [comment]
change content = "message" to embed = embed

**Comment by CrazyJaguar** [comment]
> change content = "message" to embed = embed

It's still not working.

**Comment by SilentJungle399** [comment]
Hello! Very sorry for the late reply. This library no longer serves any purpose since discord.py v2 already has implemented buttons.

Here is [a tutorial](https://www.youtube.com/watch?v=MAHJJaMulvo) to get started with buttons on discord.py v2.
